
# Returns All Streets
GET http://localhost:3000/family

### Add New Street
POST http://localhost:3000/family
Content-Type: application/json

{
    "street_id":"13",
    "house_id":"11"
}

### Add a family with id
GET http://localhost:3000/family/9

### Updates a family with id
PUT http://localhost:3000/family/9
Content-Type: application/json

{
    "street_id":"13",
    "house_id":"11"
}


### Deletes a house with id
DELETE http://localhost:3000/house/10


#* Working Routes 
# GET (indiviual & whole)
# POST 
# PUT
# DELTE